CREATE USER airflow WITH PASSWORD 'airflow';

CREATE DATABASE postgres2;

GRANT ALL PRIVILEGES ON DATABASE postgres2 TO airflow;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO airflow;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO airflow;
