apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    isDefault: true
    url: steam-sale-optimizer-postgres-1:5432
    database: monitoring_db
    user: postgres
    secureJsonData:
      password: Grizzz765>(3et37ig
    jsonData:
      sslmode: disable
      postgresVersion: 1300