name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Copy env template
      run: cp .env.template .env

    - name: Build Docker containers
      run: docker compose -f docker-compose.yml build

    - name: Start Docker containers
      run: |
        docker compose -f docker-compose.yml up -d
        echo "Waiting for services to be ready..."
        sleep 60
        docker compose ps

    - name: Wait for fastapi-app container to be healthy
      run: |
        CONTAINER_ID=$(docker compose ps -q fastapi-app)
        if [ -z "$CONTAINER_ID" ]; then
          echo "❌ fastapi-app container not found."
          docker compose ps
          exit 1
        fi

        for i in $(seq 1 30); do
          STATUS=$(docker inspect --format='{{.State.Health.Status}}' "$CONTAINER_ID" 2>/dev/null || echo "unknown")
          if [ "$STATUS" = "healthy" ]; then
            echo "✅ fastapi-app is healthy."
            exit 0
          fi
          echo "⏳ Waiting for fastapi-app to be healthy... ($i/30)"
          sleep 2
        done

        echo "❌ fastapi-app container did not become healthy in time."
        docker compose logs fastapi-app
        exit 1

    - name: Run FastAPI Unit Test (test_main_docker.py only)
      run: docker compose exec -T fastapi-app pytest tests/test_main_docker.py

    - name: Lint Python Code
      run: docker compose exec -T fastapi-app flake8 main.py

    - name: Stop Docker containers
      if: always()
      run: docker compose -f docker-compose.yml down
