name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Copy env template
      run: cp .env.template .env

    - name: Build Docker containers
      run: docker compose -f docker-compose.yml build

    - name: Start Docker containers
      run: |
        docker compose -f docker-compose.yml up -d
        echo "Waiting for services to be ready..."
        sleep 60
        docker compose ps

    - name: Check container health
      run: |
        RUNNING=$(docker inspect -f '{{.State.Running}}' $(docker compose ps -q fastapi-app))
        if [ "$RUNNING" != "true" ]; then
          echo "❌ fastapi-app is not running."
          docker compose logs fastapi-app
          exit 1
        fi

    - name: Run Unit Tests
      run: docker compose exec -T fastapi-app pytest tests/

    - name: Lint Python Code
      run: docker compose exec -T fastapi-app flake8 scripts/

    - name: Stop Docker containers
      if: always()
      run: docker compose -f docker-compose.yml down
